name: yamllint
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: yamllint
        uses: reviewdog/action-yamllint@6803b0dc8f295034a6156b924814053acb2e6f5a # v1.24.0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          yamllint_flags: 'apis/'
          fail_on_error: true
